name: python-workshop

dependencies:
  - python=3.7
  - numpy
  - scipy
  - joblib
  - scikit-learn
  - pandas
  - conda-forge::pandas-profiling
  - ipython
  - jupyter
  - pillow
  - matplotlib
  - mplleaflet
  - seaborn
  - plotly
